### ISSUE TITLE
Cannot install package growthbook-c-sharp

### ISSUE THREAD

**Issue by thisisthemurph** [growthbook/growthbook-c-sharp#10]
Hi, 

I am having trouble installing the NuGet package.

I have run the following command:

`dotnet add package growthbook-c-sharp`

As detailed here: https://docs.growthbook.io/lib/csharp

This is the error I am getting:

```
PM> dotnet add package growthbook-c-sharp
  Determining projects to restore...
  Writing C:\Users\user.name\AppData\Local\Temp\tmp1B2F.tmp
info : X.509 certificate chain validation will use the default trust store selected by .NET.
info : X.509 certificate chain validation will use the default trust store selected by .NET.
info : Adding PackageReference for package 'growthbook-c-sharp' into project 'C:\Projects\FeatureFlags\src\GrowthBookApi\GrowthBookClient.csproj'.
error: There are no versions available for the package 'growthbook-c-sharp'.
```

Does anyone know why I might be getting this error?

The package also cannot be found using the Package Manager.
I am able to install other packages through both the Package Manager and the PM Console.

### Visual Studio Info
Microsoft Visual Studio Professional 2022
Version 17.4.3
VisualStudio.17.Release/17.4.3+33205.214

### System Info
OS Name: Microsoft Windows 10 Enterprise
Version: 10.0.19045 Build 19045

**Comment by GreenVenator** [comment]
Please can you confirm that your package source is targeting nuget.org?

**Comment by thisisthemurph** [comment]
@GreenVenator amazing! For some reason, there were no sources after an update of Visual Studio.
