### ISSUE TITLE
ExperimentResult missing variation name in TrackingCallback

### ISSUE THREAD

**Issue by emiltorp** [growthbook/growthbook-c-sharp#21]
My tracking callback is as follows:
```csharp
var context = new Context
{
    ...
    TrackingCallback = new Action<Experiment, ExperimentResult>((experiment, result) =>
    {
       SendToTracking(experiment, <variationName>)
    })
};
```

The issue I'm facing is that ExperimentResult doesn't have the variation name included, even though the SDK Connection is set up that way. 

![image](https://github.com/growthbook/growthbook-c-sharp/assets/157837/d77920ca-00f6-422f-b95d-e488d6b9eeac)

In the javascript code it seems like it is obtained from `experiment.meta` but that isn't included either.

**Comment by darklordzw** [comment]
@emiltorp, good catch, we'll get it added.

**Comment by darklordzw** [comment]
@emiltorp version 1.0.0 updates this SDK to be compatible with v0.5.2 of the Growthbook SDK spec. Variation meta was added to the Experiment object, hopefully this should take care of what you're looking for.
